services:
  dbservice:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3308:3306
    networks:
      - bootapp


  
  appservice:
    build: ./boot
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/contactapp?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root

    ports:
      - 8082:8080
    networks:
      - bootapp

networks:
  bootapp:
    